# site
title: solquemal
baseurl: ""
url: "http://gallery.solquemal.com"
favicon: "/assets/ico.png"
g_analytics: UA-12345678-1

# bio
header: Gallery
desc: >
   <a href="https://solquemal.com/" target="_blank">Sol Sarratea</a>'s lastest work.

# posts
date_format: "%Y"

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  categories:
      output: true